### ISSUE TITLE
ゲームのすべての情報を共有しないようにする

### ISSUE THREAD

**Issue by syuilo** [syuilo/clova#1]
メモリを覗けば相手の手札情報も見れてしまう

**Comment by syuilo** [comment]
でもエンジンを動作させるにはすべての情報が必要だしうーーーーーーん

**Comment by ghost** [comment]
相手の手札はXX枚あるって情報だけクライアントが受け取れば十分な気が。
クライアントがボタンを押すたびにサーバの処理(ゲームロジック)がワンステップ進んで場の状態を返して行けばできそうな予感、

**Comment by syuilo** [comment]
🙏
